# Generated by Django 6.0.2 on 2026-05-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
